### ISSUE TITLE
Actiontype

### ISSUE THREAD

**Issue by belroshir** [crazywm/crazys-wm-mod#7]
Hi all,
don't know if this is an issue or not.
The Cleaning Jobs of the Movie Studio(STAGEHAND) and Farm(FARMHAND) have as Actiontype ACTION_WORKMOVIE/ACTION_WORKFARM not ACTION_WORKCLEANING as the other Buildings.
Is this wanted or not?

Regards
Belroshir

**Comment by aevojoey** [comment]
This is wanted but not final.
Stagehand uses ACTION_WORKMOVIE because she does affect movie quality.
Farmhand uses ACTION_WORKFARM because she basically cleans and fixes everything on the farm.
ACTION_WORKFARM could be considered as the girl likes working outside instead of indoors.
I will add ACTION_WORKCLEANING to both so the girl will have enjoyment modifiers for that as well as the originals.

I didn't see this until just after I pushed the changes for .06.01.21 so these will be in .22.

Update: Looking at the files again, both jobs do use both action types. I just updated the code to use both as actiontype variables.
